// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF8WolVkrGKF0ZXyrR55GBWykaNXSFvcc',
    appId: '1:571369180674:android:eb8575d1bfef3c53af611b',
    messagingSenderId: '571369180674',
    projectId: 'incomeandexpense-ce9c7',
    databaseURL: 'https://incomeandexpense-ce9c7-default-rtdb.firebaseio.com',
    storageBucket: 'incomeandexpense-ce9c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR09JeleIa3P7gJT6Vr7ijDPNlT5WYt0Y',
    appId: '1:571369180674:ios:b6a88cd92c3feae8af611b',
    messagingSenderId: '571369180674',
    projectId: 'incomeandexpense-ce9c7',
    databaseURL: 'https://incomeandexpense-ce9c7-default-rtdb.firebaseio.com',
    storageBucket: 'incomeandexpense-ce9c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterDeneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR09JeleIa3P7gJT6Vr7ijDPNlT5WYt0Y',
    appId: '1:571369180674:ios:b6a88cd92c3feae8af611b',
    messagingSenderId: '571369180674',
    projectId: 'incomeandexpense-ce9c7',
    databaseURL: 'https://incomeandexpense-ce9c7-default-rtdb.firebaseio.com',
    storageBucket: 'incomeandexpense-ce9c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterDeneme',
  );
}
